name: On PRs

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read Terraform version
        run: echo "TF_VERSION=$(cat .terraform-version)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Run Formatter
        run: make fmt-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.60.0
          cache: true

      - name: Run Linter
        run: make lint

  sec-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.4
        with:
          version: 0.68.2

      - name: Run Trivy vulnerability scanner
        run: make sec-check
